// Typing created by ingeniarius, special for doublechar.com
// Especial thanks to Naty
// 
// Copyright ingeniarius, 2011
// Copyright doublechar.com, 2011
// 
// Version: 0.9.1

String.prototype.escapeHTML=function(){return this.replace(/</g,"&lt;").replace(/>/g,"&gt;")};function Timer(){}Timer.prototype={started:false,stopped:false,startDate:null,stopDate:null,rate:1E3,refreshItems:[]};Timer.prototype.start=function(){this.startDate=new Date;this.started=true;this.stopped=false;this.tictac()};Timer.prototype.stop=function(){this.stopDate=new Date;this.stopped=true;this.refresh()};
Timer.prototype.reset=function(){this.stopDate=this.startDate=null;this.stopped=this.started=false};Timer.prototype.interval=function(){var a=0;if(this.started)a=Math.round(((this.stopped?this.stopDate:new Date)-this.startDate)/1E3);return a};Timer.prototype.refresh=function(){for(var a=0;a<this.refreshItems.length;a++)this.refreshItems[a]()};Timer.prototype.add=function(a){return typeof a=="function"?this.refreshItems.push(a):null};
Timer.prototype.tictac=function(){this.refresh();var a=this;this.started&&window.setTimeout(function(){a.tictac()},a.rate)};
function Typing(){var a=this,c=this.indicator;this.timer=new Timer;this.input=new Typing.Input;this.lesson=new Typing.Lesson;this.keyboard=new Typing.Keyboard;this.input.keydown=function(b){var d=a.input,f=b.keyCode;if(f==8){d.value=d.value.substring(0,d.value.length-1);a.errorLength>0&&a.errorLength--;d.index>0&&d.index--;a.displayProgress();a.refreshIndicators();b.preventDefault()}else if(f==16){a.keyboard.shiftMode(true);a.input.input.keyup(function(e){if(e.keyCode==16){a.keyboard.shiftMode(false);
a.input.input.unbind("keyup")}})}};this.input.keypress=function(b){var d=a.input,f=a.lesson,e=b.charCode,g=String.fromCharCode(e);if(a.mapping&&e>32)g=a.mapping[g];if(e>=32&&g&&g.length>0&&d.value.length<f.text.length){a.started||a.start();if(f.text.charAt(d.index)!=g){a.errorLength++;a.errorLength==1&&d.errors++}d.value+=g;d.total++;d.index++;a.displayProgress();a.refreshIndicators()}e==32&&b.preventDefault()};c.timer=new Typing.Indicator(function(){var b=a.timer.interval(),d=Math.round(b%60);return Math.round(b/
60)+":"+(d<10?"0"+d:d)});this.timer.add(function(){c.timer.display()});c.speedometer=new Typing.Indicator(function(){var b=a.timer.interval();if(b==0)b=1;return Math.round(a.input.total*60/b)});this.timer.add(function(){c.speedometer.display()});c.progress=new Typing.Indicator(function(){return Math.round(100*a.lesson.progress/a.lesson.text.length)});c.errors=new Typing.Indicator(function(){return a.input.errors})}
Typing.prototype={placeholder:{selectLesson:null,selectLayout:null,selectMapping:null},button:{reload:null},indicator:{progress:null,errors:null,timer:null,speedometer:null},input:null,lesson:null,timer:null,keyboard:null,mapping:null,lessonSet:[],errorLength:0,started:false};Typing.prototype.start=function(){this.timer.start();this.started=true};
Typing.prototype.finish=function(){this.stop();this.lesson.placeholder.html(['<span class="congratulation">Урок окончен!<br/>',"Вы набрали "+this.indicator.speedometer.value()+" символов за 1 минуту.<br/>","Хорошая работа!</span>"].join(""))};Typing.prototype.stop=function(){this.timer.stop();this.input.stop();this.started=false;this.keyboard.highlight("")};Typing.prototype.reset=function(){this.errorLength=0;this.timer.reset();this.input.reset();this.lesson.reset();this.started=false};
Typing.prototype.run=function(){var a=this;this.keyboard.set(Typing.layouts[0]);this.lessonSet=Typing.lessons[this.keyboard.name];this.lesson.set(this.lessonSet[0]);this.keyboard.active(this.lesson.letters);var c=$(Typing.ui.select(this.lessonSet));this.placeholder.selectLesson.html(c);c.change(function(){var d=$(this).val();a.lesson.set(a.lessonSet[d]);a.keyboard.active(a.lesson.letters);a.reset();a.render()});var b=$(Typing.ui.select(Typing.layouts));this.placeholder.selectLayout.html(b);b.change(function(){var d=
$(this).val();a.keyboard.set(Typing.layouts[d]);a.lessonSet=Typing.lessons[a.keyboard.name];c.html(Typing.ui.selectOptions(a.lessonSet));a.lesson.set(a.lessonSet[0]);a.keyboard.active(a.lesson.letters);a.reset();a.render()});b=$(Typing.ui.select(Typing.Mapping,Typing.ui.selectSimpleOptions));this.placeholder.selectMapping.html(b);b.change(function(){var d=$(this).val();a.mapping=Typing.Mapping[d]});this.button.reload.click(function(){a.reset();a.render();a.input.input.focus()});this.reset();this.render()};
Typing.prototype.render=function(){this.lesson.display();this.displayProgress();this.refreshIndicators();this.indicator.timer.display();this.indicator.speedometer.display()};Typing.prototype.refreshIndicators=function(){this.indicator.progress.display();this.indicator.errors.display()};
Typing.prototype.displayProgress=function(){var a="",c=this.input.value,b=this.lesson.text;if(c==b){this.lesson.progress=this.lesson.text.length;this.finish();return null}if(c.length>0){var d=null;for(a=0;a<c.length;a++)if(c.charAt(a)!=b.charAt(a)){d=a;break}a='<span class="typed">';if(d!=null&&d>=0){a+=b.substring(0,d).escapeHTML();a+='<span class="invalid">'+b.substring(d,c.length).escapeHTML()+"</span>";this.lesson.progress=d}else{a+=b.substring(0,c.length).escapeHTML();if(b.charAt(c.length-1)==
" "){a=a.substr(0,a.length-1);a+="&nbsp;"}this.lesson.progress=c.length}a+="</span>"}else this.lesson.progress=0;d=b.substr(c.length,1);this.errorLength==0?this.keyboard.highlight(d):this.keyboard.highlight("");a+='<span class="marker">'+(d==" "?"&nbsp;":d)+"</span>";a+=b.substr(c.length+1).escapeHTML();this.lesson.placeholder.html(a);this.lesson.placeholder[0].scrollTop=this.lesson.placeholder.find(".marker")[0].offsetTop-this.lesson.lineHeight};Typing.Input=function(){this.input=$(window);this.reset()};
Typing.Input.prototype={placeholder:null,input:null,value:"",index:0,total:0,errors:0,reset:function(){this.errors=this.total=this.index=0;this.value="";this.input.unbind();this.input.keydown(this.keydown);this.input.keypress(this.keypress);this.input.focus()},stop:function(){this.input.unbind()},keydown:function(){},keypress:function(){}};Typing.Indicator=function(a){this.value=a};Typing.Indicator.prototype={placeholder:null,value:function(){},display:function(){this.placeholder.html(this.value())}};
Typing.Lesson=function(){};Typing.Lesson.sort=function(){return Math.random()-Math.random()};
Typing.Lesson.prototype={title:"",letters:null,words:null,originText:"",wordPerLesson:null,text:"",progress:0,placeholder:null,lineHeight:0,defaultWordPerLesson:50,build:function(){if(this.words&&this.words.length>0){var a=this.words.slice(0),c=this.wordPerLesson;if(a.length>0)for(;a.length<c;)a=a.concat(a);this.text=a.sort(Typing.Lesson.sort).slice(0,c).join(" ")}else this.text=typeof this.originText=="object"?this.originText[Math.floor(Math.random()*this.originText.length)]:this.originText},set:function(a){this.title=
a.title;this.words=a.words;this.wordPerLesson=a.wordPerLesson||this.defaultWordPerLesson;this.letters=a.letters;this.originText=a.text;this.build()},reset:function(){this.build();this.placeholder[0].scrollTop=0},display:function(){var a=$("<div>!</div>");this.placeholder.append(a);this.lineHeight=a[0].clientHeight;this.placeholder.html(this.text.escapeHTML())}};
Typing.Key=function(a){this.placeholder=$('<span class="'+this.cssClass.box+'"></span>');this.modes=[];if(a){if(a.length==2){var c=new Typing.KeyMode(a[0]);this.modes.push(c);this.placeholder.append(c.placeholder);c=new Typing.KeyMode(a[1],"shift");this.modes.push(c);this.placeholder.append(c.placeholder)}}else{this.blank=true;this.placeholder.addClass(this.cssClass.blank)}};Typing.Key.prototype={placeholder:null,modes:null,blank:false,cssClass:{box:"key-box",blank:"blank"}};
Typing.KeyMode=function(a,c){this.label=a;this.mode=c||null;var b="";switch(c){case "shift":b="shift"}this.placeholder=$('<span class="'+this.cssClass.key+" "+b+'">'+a+"</span>")};Typing.KeyMode.prototype={label:"",mode:"",placeholder:null,cssClass:{key:"key",hightlight:"highlight",active:"current",blank:"blank",shiftUp:"shift up",shift:"shift"},hightlight:function(){this.placeholder.addClass(this.cssClass.hightlight)}};Typing.Keyboard=function(){this.layout={};this.shiftLayout={}};
Typing.Keyboard.prototype={placeholder:null,title:null,name:null,layout:null,html:"",cssClass:{hightlight:"highlight",active:"active"},set:function(a){var c=a.layout;this.placeholder.html("");this.name=a.name;this.title=a.title;this.layout={};for(var b in c){var d=c[b],f=$('<span class="row"></span>');this.placeholder.append(f);for(b in d){var e=d[b];a=new Typing.Key(e);f.append(a.placeholder);switch(a.modes.length){case 2:this.layout[e[0]]=a.modes[0];this.shiftLayout[e[1]]=a.modes[1]}}}},shiftMode:function(a){a?
this.placeholder.addClass("shift-mode"):this.placeholder.removeClass("shift-mode")},active:function(a){this.placeholder.find("."+this.cssClass.active).removeClass(this.cssClass.active);for(var c in a){var b=a[c];(b=this.layout[b]||this.shiftLayout[b])&&b.placeholder.addClass(this.cssClass.active)}},highlight:function(a){this.placeholder.find("."+this.cssClass.hightlight).removeClass(this.cssClass.hightlight);(a=this.layout[a]||this.shiftLayout[a])&&a.placeholder.addClass(this.cssClass.hightlight)}};
Typing.ui={};Typing.ui.select=function(a,c){var b="";b+="<select>";b+=typeof c=="function"?c(a):Typing.ui.selectOptions(a);b+="</select>";return b};Typing.ui.selectOptions=function(a){var c="",b;for(b in a)c+=['<option value="',b,'">',a[b].title,"</option>"].join("");return c};Typing.ui.selectSimpleOptions=function(a){var c="",b;for(b in a)c+=['<option value="',b,'">',b,"</option>"].join("");return c};
Typing.Mapping={"\u2014":null,"QWERTY\u2192Dvorak":{"`":"`","~":"~","1":"1","!":"!","2":"2","@":"@","3":"3","#":"#","4":"4",$:"$","5":"5","%":"%","6":"6","^":"^","7":"7","&":"&","8":"8","*":"*","9":"9","(":"(","0":"0",")":")","-":"[",_:"{","=":"]","+":"}","\\":"\\","|":"|",q:"'",Q:'"',w:",",W:"<",e:".",E:">",r:"p",R:"P",t:"y",T:"Y",y:"f",Y:"F",u:"g",U:"G",i:"c",I:"C",o:"r",O:"R",p:"l",P:"L","[":"/","{":"?","]":"=","}":"+",a:"a",A:"A",s:"o",S:"O",d:"e",D:"E",f:"u",F:"U",g:"i",G:"I",h:"d",H:"D",j:"h",
J:"H",k:"t",K:"T",l:"n",L:"N",";":"s",":":"S","'":"-",'"':"_",z:";",Z:":",x:"q",X:"Q",c:"j",C:"J",v:"k",V:"K",b:"x",B:"X",n:"b",N:"B",m:"m",M:"M",",":"w","<":"W",".":"v",">":"V","/":"z","?":"Z"},"QWERTY\u2192\u0419\u0426\u0423\u041a\u0415\u041d":{"`":"\u0451","~":"\u0401","1":"1","!":"!","2":"2","@":'"',"3":"3","#":"\u2116","4":"4",$:";","5":"5","%":"%","6":"6","^":":","7":"7","&":"?","8":"8","*":"*","9":"9","(":"(","0":"0",")":")","-":"-",_:"_","=":"=","+":"+","\\":"\\","|":"/",q:"\u0439",Q:"\u0419",
w:"\u0446",W:"\u0426",e:"\u0443",E:"\u0423",r:"\u043a",R:"\u041a",t:"\u0435",T:"\u0415",y:"\u043d",Y:"\u041d",u:"\u0433",U:"\u0413",i:"\u0448",I:"\u0428",o:"\u0449",O:"\u0429",p:"\u0437",P:"\u0417","[":"\u0445","{":"\u0425","]":"\u044a","}":"\u042a",a:"\u0444",A:"\u0424",s:"\u044b",S:"\u042b",d:"\u0432",D:"\u0412",f:"\u0430",F:"\u0410",g:"\u043f",G:"\u041f",h:"\u0440",H:"\u0420",j:"\u043e",J:"\u041e",k:"\u043b",K:"\u041b",l:"\u0434",L:"\u0414",";":"\u0436",":":"\u0416","'":"\u044d",'"':"\u042d",z:"\u044f",
Z:"\u042f",x:"\u0447",X:"\u0427",c:"\u0441",C:"\u0421",v:"\u043c",V:"\u041c",b:"\u0438",B:"\u0418",n:"\u0442",N:"\u0422",m:"\u044c",M:"\u042c",",":"\u0431","<":"\u0411",".":"\u044e",">":"\u042e","/":".","?":","}};
Typing.layouts=[{title:"Раскладка QWERTY",name:"qwerty",layout:[[["`","~"],["1","!"],["2","@"],["3","#"],["4","$"],["5","%"],null,null,["6","^"],["7","&"],["8","*"],["9","("],["0",")"],["-","_"],["=","+"]],[null,null,["q","Q"],["w","W"],["e","E"],["r","R"],["t","T"],null,null,["y","Y"],["u","U"],["i","I"],["o","O"],["p","P"],["[","{"],["]","}"]],[null,null,["a","A"],["s","S"],["d","D"],["f","F"],["g","G"],null,null,["h","H"],["j","J"],["k","K"],["l","L"],[";",":"],["'",'"']],[null,null,["z","Z"],
["x","X"],["c","C"],["v","V"],["b","B"],null,null,["n","N"],["m","M"],[",","<"],[".",">"],["/","?"],["\\","|"]]]},{title:"Раскладка Dvorak",name:"dvorak",layout:[[["`","~"],["1","!"],["2","@"],["3","#"],["4","$"],["5","%"],null,null,["6","^"],["7","&"],["8","*"],["9","("],["0",")"],["[","{"],["]","}"]],[null,null,["'",'"'],[",","<"],[".",">"],["p","P"],["y","Y"],null,null,["f","F"],["g","G"],["c","C"],["r","R"],["l","L"],["/","?"],["=","+"]],[null,null,["a","A"],["o","O"],["e","E"],["u","U"],["i",
"I"],null,null,["d","D"],["h","H"],["t","T"],["n","N"],["s","S"],["-","_"]],[null,null,[";",":"],["q","Q"],["j","J"],["k","K"],["x","X"],null,null,["b","B"],["m","M"],["w","W"],["v","V"],["z","Z"],["\\","|"]]]},{title:"Раскладка \u0419\u0426\u0423\u041a\u0415\u041d",name:"russian",layout:[[["\u0451","\u0401"],["1","!"],["2",'"'],["3","\u2116"],["4",";"],["5","%"],null,null,["6",":"],["7","?"],["8","*"],["9","("],["0",")"],["-","_"],["=","+"]],[null,null,["\u0439","\u0419"],["\u0446","\u0426"],["\u0443",
"\u0423"],["\u043a","\u041a"],["\u0435","\u0415"],null,null,["\u043d","\u041d"],["\u0433","\u0413"],["\u0448","\u0428"],["\u0449","\u0429"],["\u0437","\u0417"],["\u0445","\u0425"],["\u044a","\u042a"]],[null,null,["\u0444","\u0424"],["\u044b","\u042b"],["\u0432","\u0412"],["\u0430","\u0410"],["\u043f","\u041f"],null,null,["\u0440","\u0420"],["\u043e","\u041e"],["\u043b","\u041b"],["\u0434","\u0414"],["\u0436","\u0416"],["\u044d","\u042d"]],[null,null,["\u044f","\u042f"],["\u0447","\u0427"],["\u0441",
"\u0421"],["\u043c","\u041c"],["\u0438","\u0418"],null,null,["\u0442","\u0422"],["\u044c","\u042c"],["\u0431","\u0411"],["\u044e","\u042e"],[".",","],["\\","/"]]]},{title:"QWERTY",name:"qwerty",layout:[[["`","~"],["1","!"],["2","@"],["3","#"],["4","$"],["5","%"],["6","^"],["7","&"],["8","*"],["9","("],["0",")"],["-","_"],["=","+"],["\\","|"]],[null,null,null,["q","Q"],["w","W"],["e","E"],["r","R"],["t","T"],["y","Y"],["u","U"],["i","I"],["o","O"],["p","P"],["[","{"],["]","}"]],[null,null,null,null,
["a","A"],["s","S"],["d","D"],["f","F"],["g","G"],["h","H"],["j","J"],["k","K"],["l","L"],[";",":"],["'",'"']],[null,null,null,null,null,["z","Z"],["x","X"],["c","C"],["v","V"],["b","B"],["n","N"],["m","M"],[",","<"],[".",">"],["/","?"]]]},{title:"\u0419\u0426\u0423\u041a\u0415\u041d",name:"russian",layout:[[["\u0451","\u0401"],["1","!"],["2",'"'],["3","\u2116"],["4",";"],["5","%"],["6",":"],["7","?"],["8","*"],["9","("],["0",")"],["-","_"],["=","+"],["\\","/"]],[null,null,null,["\u0439","\u0419"],
["\u0446","\u0426"],["\u0443","\u0423"],["\u043a","\u041a"],["\u0435","\u0415"],["\u043d","\u041d"],["\u0433","\u0413"],["\u0448","\u0428"],["\u0449","\u0429"],["\u0437","\u0417"],["\u0445","\u0425"],["\u044a","\u042a"]],[null,null,null,null,["\u0444","\u0424"],["\u044b","\u042b"],["\u0432","\u0412"],["\u0430","\u0410"],["\u043f","\u041f"],["\u0440","\u0420"],["\u043e","\u041e"],["\u043b","\u041b"],["\u0434","\u0414"],["\u0436","\u0416"],["\u044d","\u042d"]],[null,null,null,null,null,["\u044f","\u042f"],
["\u0447","\u0427"],["\u0441","\u0421"],["\u043c","\u041c"],["\u0438","\u0418"],["\u0442","\u0422"],["\u044c","\u042c"],["\u0431","\u0411"],["\u044e","\u042e"],[".",","]]]},{title:"Dvorak",name:"dvorak",layout:[[["`","~"],["1","!"],["2","@"],["3","#"],["4","$"],["5","%"],["6","^"],["7","&"],["8","*"],["9","("],["0",")"],["[","{"],["]","}"]],[null,null,null,["'",'"'],[",","<"],[".",">"],["p","P"],["y","Y"],["f","F"],["g","G"],["c","C"],["r","R"],["l","L"],["/","?"],["=","+"],["\\","|"]],[null,null,
null,null,["a","A"],["o","O"],["e","E"],["u","U"],["i","I"],["d","D"],["h","H"],["t","T"],["n","N"],["s","S"],["-","_"]],[null,null,null,null,null,[";",":"],["q","Q"],["j","J"],["k","K"],["x","X"],["b","B"],["m","M"],["w","W"],["v","V"],["z","Z"]]]}];Typing.lessons={};
